const ORGANIZATION_NAME_PREFIX = "LAH"
const NEW_PATIENT_LABEL = 'NEW_PATIENT_REGISTRATION'
const OLD_PATIENT_LABEL = 'OLD_PATIENT_REGISTRATION'
const OPD_BILLING_LABEL = 'OPD_BILLING'
const DEPOSIT_LABEL = 'PATIENT_ADMISSION_DEPOSIT'
const IPD_BILLING_LABEL = 'IPD_BILLING'
const IPD_PATIENT_DISCHARGE_LABEL = 'PATIENT_DISCHARGE'

// Index Code from index_info table
const RECEIPT_INDEX_CODE = "RC"
const TRANSACTION_INDEX_CODE = "TRN"
const PURCHASE_RECEIPT_INDEX_CODE = "PUI"
const PURCHASE_RETURN_RECEIPT_INDEX_CODE = "PRI"
const SALES_RECEIPT_INDEX_CODE = "SAI"
const SALES_RETURN_RECEIPT_INDEX_CODE = "SRI"
const MULDARTA_NUMBER_INDEX_CODE ="MDN"


module.exports = {
    RECEIPT_INDEX_CODE,
    TRANSACTION_INDEX_CODE,
    ORGANIZATION_NAME_PREFIX,
    NEW_PATIENT_LABEL,
    OLD_PATIENT_LABEL,
    OPD_BILLING_LABEL,
    DEPOSIT_LABEL,
    IPD_BILLING_LABEL,
    IPD_PATIENT_DISCHARGE_LABEL,
    PURCHASE_RECEIPT_INDEX_CODE,
    PURCHASE_RETURN_RECEIPT_INDEX_CODE,
    SALES_RECEIPT_INDEX_CODE,
    SALES_RETURN_RECEIPT_INDEX_CODE,
    MULDARTA_NUMBER_INDEX_CODE,
}